from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RoleRequirements:
    slug: str
    title: str
    required_skills: set[str]
    preferred_skills: set[str]
    keywords: set[str]


ROLES: dict[str, RoleRequirements] = {
    # AI & Machine Learning
    "ai_engineer": RoleRequirements(
        slug="ai_engineer",
        title="AI Engineer",
        required_skills={
            "python",
            "machine learning",
            "deep learning",
            "tensorflow",
            "pytorch",
            "numpy",
            "pandas",
            "data preprocessing",
        },
        preferred_skills={
            "mlops",
            "kubernetes",
            "docker",
            "aws",
            "azure",
            "gcp",
            "computer vision",
            "nlp",
            "transformers",
            "llm",
            "prompt engineering",
        },
        keywords={
            "artificial intelligence",
            "ml pipelines",
            "model deployment",
            "inference",
            "optimization",
            "scalability",
        },
    ),
    "machine_learning_engineer": RoleRequirements(
        slug="machine_learning_engineer",
        title="Machine Learning Engineer",
        required_skills={
            "python",
            "scikit-learn",
            "tensorflow",
            "pytorch",
            "statistics",
            "data analysis",
            "feature engineering",
            "model evaluation",
        },
        preferred_skills={
            "spark",
            "airflow",
            "kubeflow",
            "mlflow",
            "aws sageMaker",
            "azure ml",
            "google cloud ai",
            "docker",
            "kubernetes",
        },
        keywords={
            "machine learning",
            "production ml",
            "model monitoring",
            "data pipelines",
            "automation",
            "mlops",
        },
    ),
    "data_scientist": RoleRequirements(
        slug="data_scientist",
        title="Data Scientist",
        required_skills={
            "python",
            "r",
            "statistics",
            "machine learning",
            "data analysis",
            "sql",
            "pandas",
            "numpy",
            "data visualization",
        },
        preferred_skills={
            "deep learning",
            "nlp",
            "computer vision",
            "spark",
            "tableau",
            "power bi",
            "aws",
            "git",
            "jupyter",
        },
        keywords={
            "data science",
            "analytics",
            "predictive modeling",
            "statistical analysis",
            "insights",
            "research",
        },
    ),
    
    # Cloud & DevOps
    "devops_engineer": RoleRequirements(
        slug="devops_engineer",
        title="DevOps Engineer",
        required_skills={
            "docker",
            "kubernetes",
            "ci/cd",
            "linux",
            "aws",
            "terraform",
            "ansible",
            "git",
            "bash scripting",
        },
        preferred_skills={
            "jenkins",
            "gitlab ci",
            "github actions",
            "prometheus",
            "grafana",
            "helm",
            "argocd",
            "monitoring",
            "security",
        },
        keywords={
            "devops",
            "automation",
            "infrastructure",
            "deployment",
            "monitoring",
            "scalability",
            "reliability",
        },
    ),
    "cloud_architect": RoleRequirements(
        slug="cloud_architect",
        title="Cloud Architect",
        required_skills={
            "aws",
            "azure",
            "gcp",
            "cloud architecture",
            "terraform",
            "networking",
            "security",
            "cost optimization",
        },
        preferred_skills={
            "kubernetes",
            "serverless",
            "microservices",
            "disaster recovery",
            "compliance",
            "governance",
            "multi-cloud",
            "containers",
        },
        keywords={
            "cloud",
            "architecture",
            "scalability",
            "infrastructure",
            "enterprise",
            "strategy",
            "migration",
        },
    ),
    "site_reliability_engineer": RoleRequirements(
        slug="site_reliability_engineer",
        title="Site Reliability Engineer",
        required_skills={
            "linux",
            "kubernetes",
            "monitoring",
            "automation",
            "python",
            "go",
            "aws",
            "troubleshooting",
            "performance tuning",
        },
        preferred_skills={
            "prometheus",
            "grafana",
            "jenkins",
            "terraform",
            "security",
            "networking",
            "incident response",
            "slo",
        },
        keywords={
            "sre",
            "reliability",
            "monitoring",
            "automation",
            "incident management",
            "performance",
            "uptime",
        },
    ),
    
    # Cybersecurity
    "cybersecurity_analyst": RoleRequirements(
        slug="cybersecurity_analyst",
        title="Cybersecurity Analyst",
        required_skills={
            "security",
            "network security",
            "siem",
            "incident response",
            "risk assessment",
            "compliance",
            "vulnerability assessment",
        },
        preferred_skills={
            "python",
            "splunk",
            "elastic",
            "firewall",
            "intrusion detection",
            "forensics",
            "penetration testing",
            "threat intelligence",
        },
        keywords={
            "cybersecurity",
            "security analysis",
            "threat detection",
            "risk management",
            "compliance",
            "investigation",
        },
    ),
    "security_engineer": RoleRequirements(
        slug="security_engineer",
        title="Security Engineer",
        required_skills={
            "security",
            "network security",
            "application security",
            "penetration testing",
            "vulnerability assessment",
            "risk management",
            "compliance",
        },
        preferred_skills={
            "python",
            "aws security",
            "azure security",
            "docker security",
            "kubernetes security",
            "siem",
            "threat modeling",
            "secure coding",
        },
        keywords={
            "security engineering",
            "application security",
            "penetration testing",
            "vulnerability management",
            "threat modeling",
            "secure development",
        },
    ),
    
    # Data Engineering
    "data_engineer": RoleRequirements(
        slug="data_engineer",
        title="Data Engineer",
        required_skills={
            "sql",
            "python",
            "spark",
            "etl",
            "data pipelines",
            "data modeling",
            "data warehousing",
            "big data",
        },
        preferred_skills={
            "airflow",
            "kafka",
            "aws",
            "azure",
            "gcp",
            "snowflake",
            "databricks",
            "hadoop",
            "docker",
        },
        keywords={
            "data engineering",
            "etl",
            "data pipelines",
            "big data",
            "data warehousing",
            "stream processing",
        },
    ),
    
    # Frontend Development
    "frontend_engineer": RoleRequirements(
        slug="frontend_engineer",
        title="Frontend Engineer",
        required_skills={
            "javascript",
            "html",
            "css",
            "react",
            "typescript",
            "git",
            "responsive design",
            "web performance",
        },
        preferred_skills={
            "vue",
            "angular",
            "next.js",
            "webpack",
            "testing",
            "accessibility",
            "node.js",
            "graphql",
        },
        keywords={
            "frontend",
            "react",
            "javascript",
            "typescript",
            "web development",
            "ui",
            "ux",
        },
    ),
    
    # Backend Development
    "backend_engineer": RoleRequirements(
        slug="backend_engineer",
        title="Backend Engineer",
        required_skills={
            "python",
            "java",
            "node.js",
            "sql",
            "api design",
            "rest",
            "microservices",
            "databases",
        },
        preferred_skills={
            "go",
            "rust",
            "kubernetes",
            "docker",
            "aws",
            "graphql",
            "nosql",
            "message queues",
        },
        keywords={
            "backend",
            "api",
            "microservices",
            "databases",
            "server development",
            "scalability",
        },
    ),
    
    # Product & Project Management
    "product_manager": RoleRequirements(
        slug="product_manager",
        title="Product Manager",
        required_skills={
            "product management",
            "agile",
            "scrum",
            "user research",
            "data analysis",
            "roadmapping",
            "stakeholder management",
        },
        preferred_skills={
            "technical writing",
            "analytics",
            "ux design",
            "business analysis",
            "market research",
            "a/b testing",
            "prototyping",
        },
        keywords={
            "product management",
            "strategy",
            "roadmap",
            "user experience",
            "analytics",
            "agile",
        },
    ),
    
    # Existing roles
    "software_developer": RoleRequirements(
        slug="software_developer",
        title="Software Developer",
        required_skills={
            "python",
            "java",
            "javascript",
            "data structures",
            "algorithms",
            "git",
            "sql",
            "rest",
        },
        preferred_skills={
            "docker",
            "kubernetes",
            "aws",
            "ci/cd",
            "unit testing",
            "linux",
            "system design",
        },
        keywords={
            "api",
            "microservices",
            "scalable",
            "performance",
            "debugging",
            "testing",
        },
    ),
    "data_analyst": RoleRequirements(
        slug="data_analyst",
        title="Data Analyst",
        required_skills={
            "sql",
            "excel",
            "python",
            "statistics",
            "data visualization",
            "power bi",
        },
        preferred_skills={
            "tableau",
            "pandas",
            "numpy",
            "dashboard",
            "etl",
        },
        keywords={
            "insights",
            "kpi",
            "trend",
            "forecast",
            "stakeholders",
            "reporting",
        },
    ),
    "web_developer": RoleRequirements(
        slug="web_developer",
        title="Web Developer",
        required_skills={
            "html",
            "css",
            "javascript",
            "react",
            "git",
            "rest",
        },
        preferred_skills={
            "typescript",
            "node",
            "tailwind",
            "next.js",
            "testing",
        },
        keywords={
            "responsive",
            "accessibility",
            "seo",
            "performance",
            "component",
        },
    ),
}
